### ISSUE TITLE
Go 1.15: darwin/386 is no longer supported

### ISSUE THREAD

**Issue by matthewkmayer** [gomicro/probe#15]
See https://github.com/golang/go/issues/37610 .

Goreleaser workaround: https://github.com/goreleaser/goreleaser/issues/1385#issuecomment-597611446 .

Perhaps a new version of goreleaser removes that combination by default.

**Comment by dan9186** [comment]
already fixed by https://github.com/gomicro/probe/pull/14

**Comment by matthewkmayer** [comment]
I was too slow! Thanks.
